FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
ENV ASPNETCORE_ENVIRONMENT=Server

WORKDIR /app

COPY ["OnlineChat/OnlineChat.csproj", "OnlineChat/"]
RUN dotnet restore "OnlineChat/OnlineChat.csproj"

COPY . .
RUN dotnet publish "OnlineChat/OnlineChat.csproj" -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .
EXPOSE 50743
ENTRYPOINT ["dotnet", "OnlineChat.dll"]
